--liquibase formatted sql
--changeset RomanAnnenkov:1
INSERT INTO employees (surname, name, middle_name, birth_date) VALUES ('Petrov', 'Nikolay', 'Petrovich', '1990-05-06');
INSERT INTO employees (surname, name, middle_name, birth_date) VALUES ('Sidorov', 'Gleb', 'Vasilievich', '1980-03-07');
INSERT INTO employees (surname, name, middle_name, birth_date) VALUES ('Lobov', 'Andrey', 'Sergeevich', '1985-11-16');
INSERT INTO employees (surname, name, middle_name, birth_date) VALUES ('Konev', 'Petr', 'Ivanovich', '1999-09-01');
--changeset RomanAnnenkov:2
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side1', 'spb', 2, 1);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side2', 'spb', 3, 2);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side3', 'spb', 3, 3);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side4', 'spb', 3, 4);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side5', 'spb', 3, 5);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side6', 'spb', 3, 6);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side7', 'spb', 3, 7);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side8', 'spb', 3, 8);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side9', 'spb', 3, 9);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side10', 'spb', 3, 10);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side11', 'spb', 3, 11);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side12', 'spb', 3, 12);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side13', 'spb', 3, 13);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side14', 'spb', 3, 14);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side15', 'spb', 3, 15);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side16', 'spb', 3, 16);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side17', 'spb', 3, 17);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side18', 'spb', 3, 18);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side19', 'spb', 3, 19);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side20', 'spb', 3, 20);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side21', 'spb', 3, 21);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side22', 'spb', 3, 22);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side23', 'spb', 3, 23);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side24', 'spb', 3, 24);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side25', 'spb', 3, 25);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side26', 'spb', 3, 26);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side27', 'spb', 3, 27);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side28', 'spb', 3, 28);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side28', 'spb', 3, 29);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side30', 'spb', 3, 30);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side31', 'spb', 3, 31);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side32', 'spb', 3, 32);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side33', 'spb', 3, 33);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side34', 'spb', 3, 34);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side35', 'spb', 3, 35);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side36', 'spb', 3, 36);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side37', 'spb', 3, 37);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side38', 'spb', 3, 38);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side39', 'spb', 3, 39);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side40', 'spb', 3, 40);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side41', 'spb', 3, 41);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side42', 'spb', 3, 42);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side43', 'spb', 3, 43);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side44', 'spb', 3, 44);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side45', 'spb', 3, 45);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side46', 'spb', 3, 46);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side47', 'spb', 3, 47);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side48', 'spb', 3, 48);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side49', 'spb', 3, 49);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side50', 'spb', 3, 50);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side51', 'spb', 3, 51);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side52', 'spb', 3, 2);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side53', 'spb', 3, 2);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side54', 'spb', 3, 2);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side55', 'spb', 3, 2);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side56', 'spb', 3, 2);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side57', 'spb', 3, 2);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side58', 'spb', 3, 2);
INSERT INTO offices (name, address, chief_id, organization_id) VALUES ('side59', 'spb', 3, 2);
--changeset RomanAnnenkov:3
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO One', '1', '123456701', '987654301', 'Moscow', 'SPb', 1);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Two', '2', '123456702', '987654302', 'Moscow', 'SPb', 2);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Three', '3', '123456703', '987654303', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Four', '4', '123456704', '987654304', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Five', '5', '123456705', '987654305', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Six', '6', '123456706', '987654306', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Seven', '7', '123456707', '987654307', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Eight', '8', '123456708', '987654308', 'Moscow', 'SPb', 1);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Nine', '9', '123456709', '987654309', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Ten', '10', '123456710', '987654310', 'Moscow', 'SPb', 2);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Eleven', '11', '123456711', '987654311', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twelve', '12', '123456712', '987654312', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirteen', '13', '123456713', '987654313', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourteen', '14', '123456714', '987654314', 'Moscow', 'SPb', 2);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fifteen', '15', '123456715', '987654315', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Sixteen', '16', '123456716', '987654316', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Seventeen', '17', '123456717', '987654317', 'Moscow', 'SPb', 4);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Eighteen', '18', '123456718', '987654318', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Nineteen', '19', '123456719', '987654319', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twenty', '20', '123456720', '987654320', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twenty One', '21', '123456721', '987654321', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twenty Two', '22', '123456722', '987654322', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twenty Three', '23', '123456723', '987654323', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twenty Four', '24', '123456724', '987654324', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twenty Five', '25', '123456725', '987654325', 'Moscow', 'SPb', 4);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twenty Six', '26', '123456726', '987654326', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twenty Seven', '27', '123456727', '987654327', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twenty Eight', '28', '123456728', '987654328', 'Moscow', 'SPb', 1);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Twenty Nine', '29', '123456729', '987654329', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirty', '30', '123456730', '987654330', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirty One', '31', '123456731', '987654331', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirty Two', '32', '123456732', '987654332', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirty Three', '33', '123456733', '987654333', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirty Four', '34', '123456734', '987654334', 'Moscow', 'SPb', 2);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirty Five', '35', '123456735', '987654335', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirty Six', '36', '123456736', '987654337', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirty Seven', '37', '123456737', '987654337', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirty Eight', '38', '123456738', '987654338', 'Moscow', 'SPb', 2);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Thirty Nine', '39', '123456739', '987654339', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourty', '40', '123456740', '987654340', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourty One', '41', '123456741', '987654341', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourty Two', '42', '123456742', '987654342', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourty Three', '43', '123456743', '987654343', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourty Four', '44', '123456744', '987654344', 'Moscow', 'SPb', 1);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourty Five', '45', '123456745', '987654345', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourty Six', '46', '123456746', '987654346', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourty Seven', '47', '123456747', '987654347', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourty Eight', '48', '123456748', '987654348', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fourty Nine', '49', '123456749', '987654349', 'Moscow', 'SPb', 3);
INSERT INTO organizations (full_name, short_name, inn, ogrn, post_address, legal_address, ceo_id) VALUES ('OOO Fifty', '50', '123456789', '987654321', 'Moscow', 'SPb', 4);
